#!/bin/bash
[ ${UID} -ne 0 ] && SUDO=sudo # Sudo if not root
supportedArchs=(x86_64 armv7h aarch64 i686 pentium4 any)
JOB_NAME_KEYS=(${JOB_NAME//// })

#  _____                 _
# |  ___|   _ _ __   ___| |_ ___
# | |_ | | | | '_ \ / __| __/ __|
# |  _|| |_| | | | | (__| |_\__ \
# |_|   \__,_|_| |_|\___|\__|___/
#

# Docker check

function isDocker {
  [ -n "${container}" ]
  return $?
}

# Check if our package already exists in the intended destination directory.
function checkPackageAlreadyBuilt {

  # If this is a python package, set PKGREL based on the currently installed python version
  . PKGBUILD
  if [[ ${depends[@]} =~ python ]]
  then

    echo "[${scriptName}] This package appears to be releated to python."
    echo "[${scriptName}] Setting PKGREL based on the current latest python release on this system."
    if ! grep -qs pythonPkgRel PKGBUILD
    then
      pythonPkgRel=$(find /usr/lib -mindepth 1 -maxdepth 1 -type d -name 'python*' -printf '%f\n' | sort -V | tail -n1 |grep -Eo '[0-9]' | tr -d '\n')

      if ! [ -n "${pythonPkgRel}" ]
      then
        echo "[${scriptName}] Failed to detect system latest python version. Exiting."
        exit 1
      fi

      echo -e "\npkgrel=${pythonPkgRel} # pythonPkgRel" >> PKGBUILD

    fi

  fi

  if [ -f /etc/makepkg.conf ] && [ -f PKGBUILD ]
  then
    . /etc/makepkg.conf
    . PKGBUILD


    packageFilepath="${pkgname}-${epoch}${pkgver}-${pkgrel}-${arch}${PKGEXT}"

    if [ -n "${PKGDEST}" ]
    then
      packageFilepath="${PKGDEST}/${packageFilepath}"
    fi

    if [ -f "${packageFilepath}" ]
    then
      echo "[${scriptName}] Package already built: ${packageFilepath}"
      return 0
    else
      return 1
    fi
  fi
}

# Check if the package we're about to build can already be seen in repos other
# than the name of which we're about to build into.
# (To catch AUR packages promoted to official repositories)
function checkPackageInRepos {
  pkgSearch="$( pacman -Ss "^${1}$" | grep '^[a-zA-Z]'  | grep -v "${REPONAME}")"

  [ -n "${pkgSearch}" ]
  return $?
}

# Check if the package we intend to build is already available in repos.
function checkTargetPackageExists {
  if grep -qs 'archlinux/packaging/packages' .git/config
  then
    echo "[${scriptName}] This appears to be an official package. Skipping obsoletion check."
    return
  fi

  if checkPackageInRepos ${pkgname}
  then
    echo "[${scriptName}] This AUR package may be obsoleted!"
    echo "[${scriptName}] Pacman findings:"
    while read package
    do
      echo -e "\t${package}"
    done <<< "${pkgSearch}"
    exit 1
  fi
}

# Try to get information about an AUR package
function getAurPackageInfo {
  depRepoQuery=$(curl -s -X 'GET' -H 'accept: application/json' "https://aur.archlinux.org/rpc/v5/info/${1}")
  packageBase=$(jq -r .results[].PackageBase <<< "${depRepoQuery}")

  # If we fail to resolve a package, desperately try again replacing hyphens with underscores.
  if [ -z "${packageBase}" ]
  then
    echo "[${scriptName}] Re-searching package info with underscores..." >&2
    depRepoQuery=$(curl -s -X 'GET' -H 'accept: application/json' "https://aur.archlinux.org/rpc/v5/info/${1//-/_}")
    packageBase=$(jq -r .results[].PackageBase <<< "${depRepoQuery}")
  fi

  echo "${packageBase}"
  [ -n "${packageBase}" ]
  return $?
}

# Attempt to resolve all dependencies of the package we want to build. Including AUR.
function getAllDeps {

  # If a dependency is not available in given repos assume we have to build it ourselves.
  deps=(${depends[@]} ${makedepends[@]} ${checkdepends[@]} ${depends_i686[@]} ${depends_x86_64[@]})
  for dep in ${deps[*]}
  do
    dep="$(sed -E -e 's/(<|>)=.*//g' -e 's/=.*//g' -e 's/(<|>).*//g' <<< "${dep}")" # Strip version requirements from a package name.

    # Skip any circular dependencies
    if [[ "${dep}" == "${BASENAME}" ]]
    then
      echo "[${scriptName}] Skipping circular dep ${dep}..."
      continue
    fi

    echo "[${scriptName}] Processing dep ${dep}..."
    if ! checkPackageInRepos "${dep}"
    then
      echo "[${scriptName}] Acquiring AUR dependency ${dep}..."
      hasAurDeps=1
      if [ ! -d "deps/${dep}" ]
      then
        mkdir -p deps


        # Check if we can resolve this package from a manually specified dependency
        if [ -n "${packagePreferences[${dep}]}" ]
        then
          echo "[${scriptName}] Using user preference: ${dep}=${packagePreferences[${dep}]}."
          dep="${packagePreferences[${dep}]}"
        fi

          # Ask AUR what git path the dep is under (Sometimes does not match package name 1:1)
        depRepoName=$(getAurPackageInfo "${dep}")
        if [ -z "${depRepoName}" ]
        then
          echo "[${scriptName}] Can't find package for ${dep}, may be a generic reference with multiple package providers."
          echo "[${scriptName}] If you have a preference provider consider using '--preferred ${dep}=someProviderPackage' otherwise this must be manually resolved."
          exit 1
        fi
        git clone "https://aur.archlinux.org/${depRepoName}.git" deps/${dep}
      fi

      # Invoke this script on the dependency and install it.
      pushd deps/${dep} >/dev/null 2>&1
      ${0} --start ${startTimeUnix} --install --noconfirm ${makepkgArgs[*]} -si --noconfirm --dep --needed
      popd >/dev/null 2>&1

    else
      # Check if the package exists or if its provided by something else.
      # Store the result for installation.
      if pacman -Si ${dep} >/dev/null 2>&1
      then
        depsToFetch+=("${dep}")
      else
        depRealName="$(pacman -Ss "^${dep}$" |head -n1 | cut -d' ' -f1)"
        if [ ! -z "${depRealName}" ]
        then
          depsToFetch+=("${depRealName}")
        fi
      fi

    fi
  done

  if [ -n "${depsToFetch[*]}" ]
  then
    ${SUDO} pacman -Syu --noconfirm # Sync up and upgrade.
    yes '' | ${SUDO} pacman -S --needed --asdeps ${depsToFetch[@]}
  else
    echo "[${scriptName}] No special deps required."
  fi
}

function signKeys {
  # Sign any keys passed as an argument to the script
  if [ -n "${keys}" ]
  then
    for key in ${keys[*]}
    do
      echo "[${scriptName}] Fetching pgp key: ${key}"
    gpg --recv-key ${key}
    echo "[${scriptName}] Signing pgp key: ${key}"
    gpg --lsign ${key}
    done
  fi

  # Sign any keys passed as an argument to the script (But for pacman-key)
  if [ -n "${keysPacman}" ]
  then
    for key in ${keysPacman[*]}
    do
      echo "[${scriptName}] Fetching pgp key (pacman): ${key}"
    ${SUDO} pacman-key -r ${key}
      echo "[${scriptName}] Signing pgp key (pacman): ${key}"
    ${SUDO} pacman-key --lsign-key ${key}
    done
  fi
}

# Parse .SRCINFO for information regarding the package
function parseSrcinfo {
  while read line
  do
    key=$(cut -d= -f1    <<< "${line}" | tr -d ' ')
    value=$(cut -d= -f2- <<< "${line}" | tr -d ' ')

    # Ignore empty lines
    [ -z "${line}" ] && continue

    declare -a ${key}+="(\"${value}\")" # Works but while loop does not set them globally
    echo "${key}+=(\"${value}\")"
    #echo "$key+=(\"${value}\")"
    #$key+=("${value}")
  done < .SRCINFO
}

function readSrcinfo {
  eval "$(parseSrcinfo)"
}

# Attempt to build a package
function makePackage {
   echo "[${scriptName}] Building..."

   # Check if already in repo and build deps
  if readSrcinfo
  then

    if [ -n "${validpgpkeys[*]}" ]
    then
      keys+=(${validpgpkeys[*]})
    fi

    # Fetch and sign any pgp keys this PKGBUILD intends to verify content with, plus any extras.
    signKeys

    checkTargetPackageExists
    getAllDeps

  else
    echo "[${scriptName}] Unable to read PKGBUILD"
    exit 1
  fi

   # Build our target
  CARCH=${REPOARCH} makepkg ${makepkgArgs[*]}

}

# Provision a podman container for building the desired package
function createContainer {

  echo "[${scriptName}] Creating container..."

  # Filter unfriendly characters from the container name
  CONTAINERNAME="$(tr -cd '[a-zA-Z0-9][a-zA-Z0-9_.-]' <<< "${BASENAME}")"

  # Ensure there isn't a remaining container from a previously interrupted run
  podman container rm -f -t0 "${CONTAINERNAME}" >/dev/null 2>&1


  # Make a pacman cache just for these containers
  mkdir -p "${HOME}/podman_var_cache_pacman"

  # Also remove anything in it older than 30 days
  days=30
  if [[ ${days:-30} =~ [0-9]+ ]]
  then

    # Give a tally
    echo -n "Removing packages from cache: "
    time find "${HOME}/podman_var_cache_pacman" -type f -name '*.zst' -ctime +${days:-30} | \
      tee -a pacman-cache_${days:-30}d_or_older.$(date +%s).txt | wc -l

    # Remove old packages
    time find "${HOME}/podman_var_cache_pacman" -type f -ctime +${days:-30} -name '*.zst' -delete
  fi

  # Start a container with some critical pieces passed through. Plus the host's pacman cache.
  # ulimit is specified to prevent `fakeroot` from hanging.
  podman run \
    -ti \
    -d \
    -v ${PKGDEST}:${PKGDEST} \
    -v ${0}:${0} \
    -v ${PWD}:${PWD} \
    --name ${CONTAINERNAME} \
    --hostname ${CONTAINERNAME} \
    -e BASENAME=${BASENAME} \
    -e REPOBASE=${REPOBASE} \
    -e REPONAME=${REPONAME} \
    -e REPOARCH=${REPOARCH} \
    -e    CARCH=${REPOARCH} \
    -e  PKGDEST=${PKGDEST} \
    -v ${HOME}/podman_var_cache_pacman:/var/cache/pacman \
    --userns=keep-id:uid=$(id -u),gid=$(id -g) \
    --user root \
    --ulimit nofile=1024:524288 \
    ${baseImageName} \
    bash

    ## Not included for now
    # ownership issues in rootless
    # No need
    # --network=host \
    # # Using true uid/gid instead
    # --userns=keep-id:uid=1000,gid=1000 \

  # Update and configure the environment for building.
  podman exec -w "${PWD}" ${CONTAINERNAME} pacman-key --init

  # Ignore initramfs packages to avoid generating needless images in the container.
  #podman exec -w "${PWD}" ${CONTAINERNAME} sed -i '/#IgnorePkg/a IgnorePkg = booster dracut mkinitcpio initramfs' /etc/pacman.conf

  # Use the host's mirrorlist (In case there's a local mirror or proxy we should be using)
  if [ -d /etc/pacman.d/mirrorlist ]
  then
    podman cp /etc/pacman.d/mirrorlist "${CONTAINERNAME}":/etc/pacman.d/mirrorlist
  fi

  podman exec -w "${PWD}" "${CONTAINERNAME}" pacman -Sydd linux --noconfirm --needed --ignore booster,dracut,mkinitcpio,initramfs # Alone to ignore deps

  if [ -n "${multilib}" ]
  then
    podman exec -w "${PWD}" "${CONTAINERNAME}" bash -c "echo '[multilib]'                         | tee -a /etc/pacman.conf"
    podman exec -w "${PWD}" "${CONTAINERNAME}" bash -c "echo 'Include = /etc/pacman.d/mirrorlist' | tee -a /etc/pacman.conf"
  fi

  if [ -n "${extra}" ]
  then
    podman exec -w "${PWD}" "${CONTAINERNAME}" bash -c "echo '[extra]'                            | tee -a /etc/pacman.conf"
    podman exec -w "${PWD}" "${CONTAINERNAME}" bash -c "echo 'Include = /etc/pacman.d/mirrorlist' | tee -a /etc/pacman.conf"
  fi

  # Update the container
  podman exec -w "${PWD}" "${CONTAINERNAME}" pacman -Syu --noconfirm --needed base-devel binutils debugedit fakeroot gcc git jq sudo linux linux-headers

  # Replicate this user's group ID and user ID in the container, conveniently named the same.
  podman exec -w "${PWD}" "${CONTAINERNAME}" groupadd --gid $(id -g) $(id -gn ${USER})
  podman exec -w "${PWD}" "${CONTAINERNAME}" useradd -d ${HOME} -m -u ${UID} ${USER} -g $(id -gn ${USER})
  podman exec -w "${PWD}" "${CONTAINERNAME}" chown -R ${USER} ${HOME}
  podman exec -w "${PWD}" "${CONTAINERNAME}" chown -R ${USER} ${HOME}

  # Copy the host's makepkg.conf for the build.
  podman cp /etc/makepkg.conf "${CONTAINERNAME}":/etc/makepkg.conf

  # Let the user invoke sudo inside the container
  podman exec -w "${PWD}" "${CONTAINERNAME}" bash -c "tee /etc/sudoers.d/user_${USER} <<< '${USER} ALL=(ALL) NOPASSWD: ALL'"

  # Start the build by running this script and its arguments again but inside the container.
  podman exec -w "${PWD}" -u ${USER} ${CONTAINERNAME} bash -l ${0} ${arguments[*]}
  buildCode=$?

  # Always clean up
  podman container rm -f -t0 "${CONTAINERNAME}" >/dev/null 2>&1
  exit ${buildCode}
}

#  ____             _
# | __ )  ___  __ _(_)_ __
# |  _ \ / _ \/ _` | | '_ \
# | |_) |  __/ (_| | | | | |
# |____/ \___|\__, |_|_| |_|
#             |___/

scriptName=$(basename $0)
declare -a  makepkgArgs
declare -AG packagePreferences

# Install any dependencies
$SUDO pacman -S --needed --asdeps jq

if [ -z "${CARCH}" ]
then
  ARCHITECTURE=$(uname -m)
else
  ARCHITECTURE=${CARCH}
fi

baseImageName=archlinux:latest

if [[ "${CARCH}" == aarch64 ]]
then
  baseImageName=archlinux-aarch64:latest
fi


arguments=($@) # For podman if invoked.
while [ $# -gt 0 ]
do
  case "$(tr '[:upper:]' '[:lower:]'<<<$1)" in
    -f|-force|--f|--force)
      echo "[${scriptName}] Forcing build..."
      force=1
      makepkgArgs+=(-f)
    ;;

    --dep)
      dep=1
    ;;

    --key)
      echo "[${scriptName}] ${2} will be pulled and signed for this build."
      keys+=(${2})
      shift
    ;;

    --pacmankey)
      echo "[${scriptName}] ${2} will be pulled and signed for this build. (pacman-key)"
      keysPacman+=(${2})
      shift
    ;;

    --multilib)
      echo "[${scriptName}] Multilib will be enabled."
      multilib=1
    ;;

    --extra)
      echo "[${scriptName}] Extra will be enabled."
      extra=1
    ;;

    --preferred|--preference)
      echo "[${scriptName}] Setting package preference: ${2}"
       package="$(cut -d= -f1  <<< ${2})"
      provider="$(cut -d= -f2- <<< ${2})"
      packagePreferences[${package}]="${provider}"
      echo ${packagePreferences[zfs]}
      shift
    ;;

    *)
      echo "[${scriptName}] Passing to makepkg: $1"
      makepkgArgs+=(${1})
    ;;

    esac
  shift
done

# Attempt to guess unfilled variables and set some defaults.

# When unset, assume repositories live under /repo
[ -z "${REPOBASE}" ] && export REPOBASE=/repo

# Attempt to resolve the package name from jenkins variables
if [ -z "${BASENAME}" ]
then
  if [ -n "${JOB_BASE_NAME}" ]
  then
    export BASENAME="${JOB_BASE_NAME}"
  elif [ -n "${JOB_NAME_KEYS}" ]
  then
    export BASENAME="${JOB_NAME_KEYS[-1]}"
  fi
fi

# Attempt to resolve the intended architecture for this package from jenkins variables
if [ -z "${REPOARCH}" ]
then

  if [ ${#JOB_NAME_KEYS[*]} -gt 0 ]
  then

    for key in ${!JOB_NAME_KEYS[*]}
    do
      if [[ ${supportedArchs[@]} =~ ${JOB_NAME_KEYS[${key}]} ]]
      then
        REPOARCH="${JOB_NAME_KEYS[${key}]}"
        REPOARCHINDEX=${key}
      fi
    done
  fi
fi

# Attempt to resolve the name of the repository by looking at the directory before a discovered architecture.
if [ -z "${REPONANE}" ]
then
  if [ -n "${REPOARCHINDEX}" ]
  then
    REPONAME=${JOB_NAME_KEYS[$(((${REPOARCHINDEX}-1)))]}
  fi
fi

if [ -z "${PKGDEST}"  ]
then
  PKGDEST_PROPOSED="${REPOBASE}/${REPONAME}/${REPOARCH}"
  if [ -d ${PKGDEST_PROPOSED} ]
  then
    export PKGDEST=${PKGDEST_PROPOSED}
  else
    echo "[${scriptName}] No PKGDEST provided and autodiscovered directory tree does not exist: ${PKGDEST_PROPOSED}."
    exit 1
  fi
fi

echo "[${scriptName}] REPOBASE=${REPOBASE}"
echo "[${scriptName}] REPONAME=${REPONAME}"
echo "[${scriptName}] REPOARCH=${REPOARCH}"
echo "[${scriptName}] BASENAME=${BASENAME}"
echo "[${scriptName}]  PKGDEST=${PKGDEST}"

[ -z "${REPONAME}" ] && { echo "[${scriptName}] Cannot proceed, missing critical var: REPONAME" ; exit 1 ;}
[ -z "${REPOARCH}" ] && { echo "[${scriptName}] Cannot proceed, missing critical var: REPOARCH" ; exit 1 ;}

# Check if we have already got the package
# Skip this check for -git packages, or when -force/-f is specified.
if checkPackageAlreadyBuilt
then
  if [ -n "${force}" ]
  then
    echo "[${scriptName}] Forcing rebuild..."

  elif [ -n "${dep}" ]
  then
    echo "[${scriptName}] Continuing so makepkg can install this as a dependency..."

    # If our repo is signed, make sure we trust it.
    if [ -f "${PKGDEST}/${REPONAME}.db.sig" ]
    then
      set -o pipefail
      repoPublicKey=$(pacman-key --verify "${PKGDEST}/${REPONAME}.db.sig" 2>&1 | grep -Po '[A-F0-9]{40}')
      repoPublicKeyVerifyOutcome=$?
      set +o pipefail
      if [ -n "${repoPublicKey}" ] && [ ${repoPublicKeyVerifyOutcome} -gt 0 ]
      then
        echo "[${scriptName}] Trusting this repository's signature with pacman-key so existing package files may be used."
        keysPacman+=(${repoPublicKey})
        signKeys
      fi
    fi

  elif [[ ${BASENAME} =~ -git$ ]]
  then
    echo "[${scriptName}] This is a git package. Continuing in case of new release."

  else
    echo "[${scriptName}] Use -f/-force to force a rebuild."
    exit 13
  fi
fi

# Check environment is ready for podman activities
# and either build the package or make a container to do so.
if isDocker
then
  if [ -d "${PKGDEST}" ]
  then
    makePackage
  else
    echo "[${scriptName}] Could not determine the intended package directory."
    exit 1
  fi

else
  if ! command -v podman >/dev/null
  then
    echo "Can't find podman in PATH, is it installed?"
    exit 1
  fi

  createContainer
fi
